# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x07greeter\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x44\x65layedReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x86\x02\n\x07Greeter\x12\x38\n\x08SayHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\"\x00\x12?\n\x0fServerSaysHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply0\x01\x12\x41\n\x0f\x43lientSaysHello\x12\x15.greeter.HelloRequest\x1a\x15.greeter.DelayedReply(\x01\x12=\n\x0bHybridHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=26
  _globals['_HELLOREQUEST']._serialized_end=72
  _globals['_HELLOREPLY']._serialized_start=74
  _globals['_HELLOREPLY']._serialized_end=103
  _globals['_DELAYEDREPLY']._serialized_start=105
  _globals['_DELAYEDREPLY']._serialized_end=136
  _globals['_GREETER']._serialized_start=139
  _globals['_GREETER']._serialized_end=401
# @@protoc_insertion_point(module_scope)
